### ISSUE TITLE
Request for documentation around Repo constructor

### ISSUE THREAD

**Issue by canadaduane** [automerge/hypermerge#19]
I think the old interface (0.3.x) was to use something like `import Hypermerge from 'hypermerge'` while it seems the most common way to use the latest Hypermerge is `import { Repo } from 'hypermerge'`. However, there aren't many hints as to how to do that in the code.

https://github.com/automerge/hypermerge/blob/master/src/Repo.ts#L38

The Chat example also references the "old way":

https://github.com/automerge/hypermerge/blob/master/examples/chat/channel.js

**Comment by canadaduane** [comment]
It might also be a good time to change all the "id: string" params to "url: string".

**Comment by pvh** [comment]
This now has some types! I'm going to close this out and open a separate issue to remove / replace the old chat example code.
