### ISSUE TITLE
Change "repo.replicate" to "repo.connect"?

### ISSUE THREAD

**Issue by canadaduane** [automerge/hypermerge#20]
I find the terminology "replicate" a tad confusing when called like this:

```
repo.replicate(swarm);
```

At first blush, my interpretation was that the repository I had created would make multiple copies of a swarm.

I wonder if `repo.connect(swarm)` might be clearer?

**Comment by pvh** [comment]
This is not great terminology, but it's hoisted from dat-land projects.
