### ISSUE TITLE
please update documentation

### ISSUE THREAD

**Issue by crostine** [automerge/hypermerge#26]
I am having a hard time figuring out how to properly use this module, the documentation is for version 1.0.2 but the current version is 0.4.0

even the "basic setup" in the readme is not working...
```js
const { Repo } = require( "hypermerge" );
const repo = new Repo({ path, storage });
// TypeError: Repo is not a constructor
// Repo is undefined
```

am I doing something wrong?

**Comment by crostine** [comment]
Apparently on npm the version of the module is 0.4.0.

**Comment by pvh** [comment]
Thanks for the feedback! I should spend a bit of time updating READMEs and cutting a new release on hypermerge for sure. I'm currently living off the github master which is a bit unhealthy. I'm going to leave this issue open to remind me and schedule some time for this some time this week.

**Comment by decentral1se** [comment]
That would be great! Thanks a lot @pvh. I'm going to try using this library with some friends soon and can hopefully help out with some documentation patches where things are fuzzy (and we actually know whats going on :sweat_smile:)

**Comment by crapthings** [comment]
yes need more information

**Comment by falafeljan** [comment]
any way we can help, @pvh? i'm relatively new to hypermerge, but as i'm using it for my research, i'd be glad to work on the docs 🤝

**Comment by pvh** [comment]
Sure. Probably the best short-term approach is to jump into the Automerge Slack and ask questions about anything confusing and we can work together to get the docs whipped into shape.

**Comment by 100ideas** [comment]
@falafeljan I am in the same boat with you. To get a little familiar with the api of hypermerge and automerge, I put together some simple playgrounds at repl.it. The hypermerge example pulls hypermerge from this repo so its up to date. Please fork and extend!

- https://repl.it/@100ideas/playing-with-hypermerge
- https://repl.it/@100ideas/playing-with-automerge (v0.12.1)
