### ISSUE TITLE
How to build with hypermerge a secure and privacy-centered p2p collaboration tool?

### ISSUE THREAD

**Issue by marcoippolito** [automerge/hypermerge#78]
I read "While the DAT community has done a lot of work to secure their tool set, zero effort has been made with hypermerge itself to deal with security and privacy concerns. Due to the secure nature of the tools its built upon a properly audited and secure version of this library would be possible in the future."

How to build with hypermerge a secure and privacy-centered p2p collaboration tool?

Looking forward to your kind hints and suggestions.

Marco

**Comment by J-P-S-O** [comment]
Refering to privacy, a big issue with p2p systems is that they expose the users' ips easily. It would be cool if there was an onion like tool built over dat, hypercore and hypermerge.
