### ISSUE TITLE
Hypermerge Installation Problems

### ISSUE THREAD

**Issue by marcoippolito** [automerge/hypermerge#79]
I tried to install hypermerge in Ubuntu 18.04.4 Desktop but got a series of errors like this one:

    ../src/socket_wrap.cc:99:45: error: no matching function for call to ‘v8::Value::ToObject()’
       99 |   Local<Object> context = info[0]->ToObject();
            |                                             ^

I attach here the complete log of the installation: 
[hypermergeInstallConfig.txt](https://github.com/automerge/hypermerge/files/4840530/hypermergeInstallConfig.txt)

vue info

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
      Browsers:
        Chrome: 83.0.4103.116
        Firefox: 77.0.1

While installing automerge and hypercore one by one doesn't produce any errors:

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ npm install automerge
    npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies 
    yourself.
    npm WARN gun@0.2020.520 requires a peer of @gooddollar/react-native-webview-crypto@^0.* but none is installed. You 
    must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/vue-cli-plugin-electron-builder
    /node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted  
    {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted     
    {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    + automerge@0.14.1
    added 5 packages from 5 contributors, removed 8 packages and audited 2303 packages in 11.847s

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ npm install hypercore

    > fd-lock@1.1.0 install /home/marco/webMatters/vueMatters/GGC/node_modules/fd-lock
    > node-gyp-build

    npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies  
    yourself.
    npm WARN gun@0.2020.520 requires a peer of @gooddollar/react-native-webview-crypto@^0.* but none is installed. 
    You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/vue-cli-plugin-electron-builder
    /node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted   
    {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted    
    {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    + hypercore@9.4.1
    added 111 packages from 44 contributors, removed 11 packages, updated 9 packages and audited 2376 packages in 23.058s

I'm having the same installation problems even if I first install fetch-libutp:

    (base) marco@pc01:~/webMatters/vueMatters/GGC$ npm run fetch-libutp
    npm ERR! missing script: fetch-libutp

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/marco/.npm/_logs/2020-07-21T09_01_35_095Z-debug.log
    (base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn run fetch-libutp
    yarn run v1.22.4
    error Command "fetch-libutp" not found.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    (base) marco@pc01:~/webMatters/vueMatters/GGC$ yarn add utp-native
    yarn add v1.22.4
    $ npx npm-force-resolutions
    npx: installed 5 in 0.782s
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix   
    package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning,      
    remove package-lock.json.
    [1/4] Resolving packages...
    warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@1.2.0"
    [2/4] Fetching packages...
    warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/marco   
    /.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity 
    /node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic  
    behavior, skipping.
    warning Pattern ["utp-native@^2.2.1"] is trying to unpack in the same destination "/home/marco/.cache/yarn/v6/npm-utp-native-   
    2.2.1-6d33feba04bfe49b368bad05555703f9728b6e63-integrity/node_modules/utp-native" as pattern ["utp-native@^2.1.7","utp- 
    native@^2.1.3"]. This could result in non-deterministic behavior, skipping.
    
    info fsevents@2.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
    warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
    warning " > gun@0.2020.520" has unmet peer dependency "@gooddollar/react-native-webview-crypto@^0.*".
    warning " > gun@0.2020.520" has unmet peer dependency "bufferutil@^4.0.1".
    warning " > gun@0.2020.520" has unmet peer dependency "utf-8-validate@^5.0.2".
    warning "http-proxy-middleware > http-proxy > follow-redirects@1.12.0" has unmet peer dependency "debug@^3.0.0 || ^4.0.0".
    warning " > rxdb@9.3.0" has unmet peer dependency "rxjs@^6.5.4".
    warning "tiptap-extensions > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "y-protocols@^0.2.0".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-model@^1.7.1".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-state@^1.2.3".
    warning " > y-prosemirror@0.3.5" has unmet peer dependency "prosemirror-view@^1.9.10".
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 1 new dependency.
    info Direct dependencies
    └─ utp-native@2.2.1
    info All dependencies
    └─ utp-native@2.2.1
    $ electron-builder install-app-deps
      • electron-builder  version=22.7.0
      • rebuilding native dependencies  dependencies=abstract-socket@2.1.1, bufferutil@4.0.1, canvas@2.6.1, fd-lock@1.1.1,    
    sodium-native@3.2.0, utf-8-validate@5.0.2, utp-native@2.2.1, websocket@1.0.31
                                        platform=linux
                                        arch=x64
      • rebuilding native dependency  name=bufferutil version=4.0.1
      • rebuilding native dependency  name=abstract-socket version=2.1.1
      • rebuilding native dependency  name=canvas version=2.6.1
      • rebuilding native dependency  name=fd-lock version=1.1.1
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=utf-8-validate version=5.0.2
      • rebuilding native dependency  name=utp-native version=2.2.1
      • rebuilding native dependency  name=websocket version=1.0.31
    Done in 19.06s.

[hypermergeInstallation-02.txt](https://github.com/automerge/hypermerge/files/4952463/hypermergeInstallation-02.txt)

How to solve the problem with hypermerge?
Looking forward to your kind help.
Marco

**Comment by pvh** [comment]
Closing this out because I assume you've either sorted out your build issue or moved on -- it looks like you have trouble with the libUTP compilation.
