### ISSUE TITLE
Types Errors: Cannot use namespace 'DocUrl' as a type, Parameter 'state' implicitly has an 'any' type in channel.ts

### ISSUE THREAD

**Issue by raphael10-collab** [automerge/hypermerge#83]
I just imported in the electron app I'm building the channel.ts file of the chat example.
And I get these errors:

    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/services/p2p/chat/channel.ts(20,24):
    20:24 Cannot use namespace 'DocUrl' as a type.
        18 | class Channel extends EventEmitter {
        19 |   public readonly nick: string
      > 20 |   public readonly url: DocUrl
           |                        ^
        21 | 
        22 |   private _doc?: Doc<ChatChannel>
        23 |   private repo: Repo
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/services/p2p/chat/channel.ts(23,17):
    23:17 Cannot use namespace 'Repo' as a type.
        21 | 
        22 |   private _doc?: Doc<ChatChannel>
     > 23 |   private repo: Repo
             |                 ^
        24 |   private swarm?: any
        25 | 
        26 |   constructor(nick: string, channelKey?: string) {
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/services/p2p/chat/channel.ts(45,32):
    45:32 Cannot use namespace 'DocUrl' as a type.
            43 |     } else {
        44 |       console.log(`Searching for chat channel ${channelKey} on network...`)
     > 45 |       this.url = channelKey as DocUrl
             |                                ^
       46 |     }
       47 |   }
        48 | 
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/services/p2p/chat/channel.ts(59,46):
    59:46 Parameter 'state' implicitly has an 'any' type.
        57 |     })
        58 | 
      > 59 |     this.repo.change<ChatChannel>(this.url, (state) => {
           |                                              ^
        60 |       state.messages[Date.now()] = {
        61 |         joined: true,
        62 |         nick: this.nick,
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/services/p2p/chat/channel.ts(72,48):
    72:48 Parameter 'state' implicitly has an 'any' type.
        70 |     const message = line.trim()
        71 |     if (message.length > 0) {
      > 72 |       this.repo.change<ChatChannel>(this.url, (state) => {
           |                                                ^
        73 |         state.messages[Date.now()] = {
        74 |           content: message,
        75 |           nick: this.nick,
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/types/hyperswarm.d.ts(8,18):
    8:18 The expression of an export assignment must be an identifier or qualified name in an ambient context.
         6 |   export type SocketType = 'tcp' | 'utp'
         7 | 
      >  8 |   export default (options?: Options) => Hyperswarm
           |                  ^
         9 | 
        10 |   export interface Options {
        11 |     /** Optionally overwrite the default set of bootstrap servers */
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/types/hyperswarm.d.ts(8,41):
    8:41 'Hyperswarm' only refers to a type, but is being used as a value here.
         6 |   export type SocketType = 'tcp' | 'utp'
         7 | 
      >  8 |   export default (options?: Options) => Hyperswarm
           |                                         ^
         9 | 
        10 |   export interface Options {
        11 |     /** Optionally overwrite the default set of bootstrap servers */
    ERROR in /home/marco/webMatters/electronMatters/GGC-Electron/src/types/hyperswarm.d.ts(70,20):
    70:20 Interface 'Hyperswarm' incorrectly extends interface 'EventEmitter'.
      The types returned by 'removeAllListeners(...)' are incompatible between these types.
        Type 'void' is not assignable to type 'this'.
          'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.
        68 |   }
        69 | 
      > 70 |   export interface Hyperswarm extends EventEmitter {
           |                    ^
        71 |     join(dk: Buffer, options?: JoinOptions): void
        72 |     leave(dk: Buffer): void
        73 |     on<K extends keyof SwarmEvents>(name: K, cb: SwarmEvents[K]): this
    Version: typescript 3.9.7
    Time: 4236ms

 vue info

    Environment Info:

      System:
        OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
        Yarn: 1.22.5 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Browsers:
        Chrome: 85.0.4183.83
        Firefox: 80.0
      npmPackages:
        @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
        @vue/babel-plugin-transform-vue-jsx:  1.1.2 
        @vue/babel-preset-app:  4.4.6 
        @vue/babel-preset-jsx:  1.1.2 
        @vue/babel-sugar-functional-vue:  1.1.2 
        @vue/babel-sugar-inject-h:  1.1.2 
        @vue/babel-sugar-v-model:  1.1.2 
        @vue/babel-sugar-v-on:  1.1.2 
        @vue/cli-overlay:  4.4.6 
        @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-e2e-cypress: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-router: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-typescript: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-unit-mocha: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6 
        @vue/cli-service: ~4.4.0 => 4.4.6 
        @vue/cli-shared-utils:  4.4.6 
        @vue/component-compiler-utils:  3.2.0 
        @vue/preload-webpack-plugin:  1.1.2 
        @vue/test-utils: ^1.0.3 => 1.0.3 
        @vue/web-component-wrapper:  1.2.0 
        babel-helper-vue-jsx-merge-props:  2.0.3 
        typescript: ^3.9.7 => 3.9.7 
        vue: ^2.6.11 => 2.6.11 
        vue-class-component: ^7.2.5 => 7.2.5 
        vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
        vue-hot-reload-api:  2.3.4 
        vue-i18n: ^8.20.0 => 8.20.0 
        vue-loader:  15.9.3 
        vue-property-decorator: ^9.0.0 => 9.0.0 
        vue-router: ^3.2.0 => 3.3.4 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.11 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
        vuex: ^3.5.1 => 3.5.1 
        vuex-class: ^0.3.2 => 0.3.2 
      npmGlobalPackages:
        @vue/cli: 4.4.6

**Comment by pvh** [comment]
Does the example code work in situ? It's possible that it bit-rotted but I suspect your environment has some issues.

**Comment by raphael10-collab** [comment]
Hi @pvh !!

The chat example within the hypermerge folder works fine:

![image](https://user-images.githubusercontent.com/70313067/92393531-5412ff00-f120-11ea-9c55-48e0fcb22c6c.png)

While n the electron.js app I'm developing, after resolving previous problems with hypermerge installation ( https://github.com/automerge/hypermerge/issues/82 ), I installed all the packages used in the chat example,
but I get the above errors .

What elements and aspects should I check to understand how to solve the problem?

**Comment by raphael10-collab** [comment]
I closed this issue and open another related one
