### ISSUE TITLE
Hypermerge uses an old version of Hypercore

### ISSUE THREAD

**Issue by raphael10-collab** [automerge/hypermerge#88]
On this discussion it emerged that Hypermerge uses an old version of Hypercore: https://github.com/hyperswarm/hyperswarm/issues/70

Would you be so kind in trying to upgrade the hypercore's version used by hypermerge to the latest?

**Comment by pvh** [comment]
I'm not sure when I'd have time to do so, but I'd encourage you to give it a shot and send a PR!
